trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: 'git push --prune https://$(ghPat)@github.com/cloudyr/AzureKeyVault +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*'
  displayName: 'copy to cloudyr'
